version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # backend:
  #   build: .
  #   command: sh -c "npm run build && npm run start:prod"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  pgdata:
